name: HA Version Sync Check

on:
  pull_request:
    paths:
      - hacs.json
      - requirements_test.txt
      - .devcontainer/.env
      - .github/workflows/*.yml
      - script/ha-version-sync
      - script/setup/bootstrap
  push:
    branches:
      - main
    paths:
      - hacs.json
      - requirements_test.txt
      - .devcontainer/.env
      - .github/workflows/*.yml
      - script/ha-version-sync
      - script/setup/bootstrap

permissions: {}

jobs:
  check-ha-version-sync:
    name: Ensure HA version sources are in sync
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate HA version sync
        run: ./script/ha-version-sync
